### ISSUE TITLE
Horizontal Gauges - How to create

### ISSUE THREAD

**Issue by MWZotti** [v-i-s-h/PiIoT-dashboard#2]
How did you create the horizontal gauges in your display and add them to freeboard as a widget?

**Comment by v-i-s-h** [comment]
I didn't really understand what you meant by horizontal gauges. This project just uses freeboard for all visualization. And if freeboard supports horizontal gauge plugins, then you can make it work.

**Comment by MWZotti** [comment]
Sorry,
    I mixed up your dashboard with another github user.
